### ISSUE TITLE
AssertionError: The image size in a batch should be the same.

### ISSUE THREAD

**Issue by Rocomla** [w1oves/Rein#74]
**I met this error in the 4000th iteration during my first training，then i modified the cfg:**

 _scales=[int(512 * x * 0.1) for x in range(5, 21)] ——> scales=[int(512 * x * 0.1) for x in range(10, 21)]_

**I encountered this error again in the 10000th iteration during my second training.The length and width of each image in my dataset are both greater than 1024.How can i deal with this？**

_Traceback (most recent call last):
  File "/public/home/peekaboo/Rein/tools/train.py", line 119, in <module>
    main()
  File "/public/home/peekaboo/Rein/tools/train.py", line 115, in main
    runner.train()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 294, in run
    self.runner.val_loop.run()
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 373, in run
    self.run_iter(idx, data_batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/runner/loops.py", line 393, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/wrappers/distributed.py", line 137, in val_step
    return self.module.val_step(data)
  File "/opt/conda/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 132, in val_step
    data = self.data_preprocessor(data, False)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mmseg/models/data_preprocessor.py", line 136, in forward
    assert all(input_.shape[1:] == img_size for input_ in inputs),  \
AssertionError: The image size in a batch should be the same._

**Comment by w1oves** [comment]
It seems the issue occurs during validation. Could you please check if the dimensions of your inference dataset are consistent? I suggest you set a breakpoint at `/opt/conda/lib/python3.10/site-packages/mmseg/models/data_preprocessor.py:136`.

**Comment by Rocomla** [comment]
**Thanks,it was seemly soved.But i notice the validation information during my training(for a binary segmentation task):**
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background | 100.0 | 100.0 |
|  defects   |  nan  |  nan  |
+------------+-------+-------+
Is this normal?How should i deal with this?Look forward to your reply. @w1oves 

************************************************************************************************************************************
**This is how i register my custom dataset：**

```
import mmengine.fileio as fileio
from mmseg.registry import DATASETS
#from .basesegdataset import BaseSegDataset
from mmseg.datasets import BaseSegDataset

@DATASETS.register_module()
class IndustrialDefectsDataset(BaseSegDataset):
    METAINFO = dict(
        classes=('background', 'defects'),
         palette=[[0, 0, 0], [255, 255, 255]]
    )

    def __init__(self,
                 img_suffix='.bmp',
                 seg_map_suffix='.bmp',
                 reduce_zero_label=False,
                 **kwargs) -> None:
        super().__init__(
            img_suffix=img_suffix,
            seg_map_suffix=seg_map_suffix,
            reduce_zero_label=reduce_zero_label,
            **kwargs)
        assert fileio.exists(
            self.data_prefix['img_path'], backend_args=self.backend_args)
```

**Comment by w1oves** [comment]
The information you provided is not sufficient for me to pinpoint the issue. I can only offer some suggestions:
* Please double-check if the annotations for defects in your label files are indeed labeled as "1".
* Try printing the unique values and distribution of the label data as it is being read by the network during training.
This might give us some clues about what's going wrong.
